INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (1, 'Bread - Hamburger Buns', 6.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (2, 'Muffin Batt - Ban Dream Zerio', 5.95, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (3, 'Pastry - Chocolate Bake', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (4, 'Placemat - Scallop, White', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (5, 'Sauerkraut', 7.34, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (6, 'Wine - Mondavi Coastal Private', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (7, 'Pepper - Chilli Seeds Mild', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (8, 'Straw - Regular', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (9, 'Chesse - Colby', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (10, 'Criossant - Raw - Mini', 5.14, 1);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (11, 'Coffee - Premium Blend', 8.99, 2);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (12, 'Tea - Green Organic', 4.50, 2);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (13, 'Milk - Whole 1L', 3.25, 2);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (14, 'Eggs - Free Range Dozen', 5.99, 3);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (15, 'Butter - Unsalted 250g', 4.75, 3);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (16, 'Cheese - Cheddar Block', 6.50, 3);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (17, 'Yogurt - Greek Style', 4.25, 4);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (18, 'Cereal - Granola Mix', 7.80, 4);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (19, 'Orange Juice - Fresh', 3.99, 4);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (20, 'Bananas - Organic Bunch', 2.50, 5);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (21, 'Apples - Red Delicious', 4.75, 5);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (22, 'Chicken Breast - Boneless', 12.99, 5);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (23, 'Rice - Basmati 1kg', 8.50, 6);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (24, 'Pasta - Spaghetti 500g', 3.25, 6);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (25, 'Tomato Sauce - Organic', 4.99, 6);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (26, 'Olive Oil - Extra Virgin', 9.75, 7);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (27, 'Garlic - Fresh Bulb', 1.50, 7);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (28, 'Onions - Yellow 1kg', 2.25, 7);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (29, 'Potatoes - Russet 2kg', 5.50, 8);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (30, 'Carrots - Baby Organic', 3.75, 8);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (31, 'Broccoli - Fresh Head', 4.25, 8);
INSERT INTO customer_purchases (id, product, price, customer_id) VALUES (32, 'Salmon - Atlantic Fillet', 18.99, 9);

